Fix/specialty carousel
VinITAAcademy/b23_dv_dark pull request #107
Opened 2024-01-28 19:07 UTC by KateChens

Пофіксила візуальну складову переключання карток слайдеру зправа-наліво та витікаючі з цього виправлення баги

2024-01-28 19:12 UTC, YevheniiRybin commented on src/css/style.css
>          margin-top: 0;
треба об'єднати margin

2024-01-28 19:25 UTC, KateChens commented on src/css/style.css
>          margin-top: 0;
done

2024-01-28 20:02 UTC, YevheniiRybin approved these changes

2024-01-29 12:42 UTC, VitaliyBogdanuk requested changes

2024-01-29 12:44 UTC, KateChens commented on src/js/script.js
> +document.onreadystatechange = function (e) {
Це код для лоадера, щоб працював. Він нам не потрібен (код) чи розкоментувати?

2024-01-29 18:22 UTC, VitaliyBogdanuk commented on src/js/script.js
> +document.onreadystatechange = function (e) {
Або розкоментуйте щоб він працював або видаліть

2024-01-30 15:58 UTC, VitaliyBogdanuk commented
@KateChens @hollyts123 conflict

2024-01-30 16:35 UTC, KateChens commented
> @KateChens @hollyts123 conflict

resolved

2024-02-01 15:36 UTC, merged