title was centered
VinITAAcademy/b23_dv_dark pull request #124
Opened 2024-03-11 18:42 UTC by YevheniiRybin

the title of the "We provide"-section was centered

2024-03-11 18:44 UTC, SergeyKorol1982 approved these changes

2024-03-11 20:30 UTC, KateChens approved these changes

2024-03-13 18:22 UTC, VitaliyBogdanuk requested changes

2024-03-13 19:40 UTC, YevheniiRybin commented on src/css/style.css
> +        right: 25px
додав

2024-03-14 15:59 UTC, merged