1.1 develop block header
VinITAAcademy/b23_dv_dark pull request #20
Opened 2024-01-09 16:25 UTC by SergeyKorol1982

2024-01-10 12:02 UTC, KateChens requested changes
1 картинки зараз вже в папці асетс
2 використати бьютіфай для css, щоб пробіли між стилями гарні були
3 на девелоп наразі колір --background-white став --white. Тому при мерджі треба прослідкувати щоб змінна цього кольору була актуальна, саме --white
Можливо щось ще пропустила, бо маю трохи температури)

2024-01-10 15:41 UTC, YevheniiRybin requested changes
Наскільки я зрозумів, нам потрібно прописувати весь ланцюжок стилів

2024-01-10 22:19 UTC, VitaliyBogdanuk commented
@SergeyKorol1982 @hollyts123 
внесіть зміни на своїй гілці згідно коментарів

2024-01-11 09:31 UTC, SergeyKorol1982 commented
1 картинки зараз вже в папці асетс - **перенесено**
2юю використати бьютіфай для css, щоб пробіли між стилями гарні були - **змінено**
3ю на девелоп наразі колір --background-white став --white. Тому при мерджі треба прослідкувати щоб змінна цього кольору була актуальна, саме --white - **змінено**
4. Наскільки я зрозумів, нам потрібно прописувати весь ланцюжок стилів - **змінено**

2024-01-11 11:09 UTC, YevheniiRybin approved these changes

2024-01-11 16:22 UTC, KateChens approved these changes

2024-01-11 16:40 UTC, SergeyKorol1982 commented
1. привів код index.html у відповідність 
2. видалив закоментований код в CSS

2024-01-11 17:33 UTC, hollyts123 requested changes
Виправити
![Screenshot_1](https://github.com/VinITAAcademy/b23_dv_dark/assets/58187694/71c17231-fb1f-4ab2-85fe-061bb77e73c6)

2024-01-11 17:44 UTC, hollyts123 approved these changes

2024-01-11 22:31 UTC, merged