Update quote block styles
VinITAAcademy/b23_dv_dark pull request #27
Opened 2024-01-11 21:38 UTC by DariaShkolnik

2024-01-11 21:59 UTC, lizzccx approved these changes

2024-01-11 22:01 UTC, lizzccx approved these changes

2024-01-11 22:12 UTC, KateChens requested changes
1. index.html - 51 стрічка. Написати текст в р з нової стрічки, адже вона дуже довга. Закриваючий тег р перенести з нової стрічки теж.
2. Певно ти поправяла пробіли, зачепила блок conditions of participation start і з 128 стрічки р-шки негарно поїхали. Передивись р цього блоку
3. В футері зачепились footer-main-icon-box - поперенось щоб i в а були з нових стрічок, а то поки відображає криво

2024-01-11 22:34 UTC, VitaliyBogdanuk commented
@DariaShkolnik @hollyts123 
пробіть командою одинакові налаштування ІДЄ, бо це перевіряти - це біль.

2024-01-12 19:14 UTC, VitaliyBogdanuk requested changes

2024-01-12 19:14 UTC, VitaliyBogdanuk commented on src/css/style.css
>          background: repeating-linear-gradient(90deg, #000A24 0 3px,#0000 0 12px)
відсутня ";"

2024-01-12 19:14 UTC, VitaliyBogdanuk commented on src/css/style.css
>      background:
пропишіть в 1ну стрічку та відсутня ";"

2024-01-12 19:14 UTC, VitaliyBogdanuk commented on src/css/style.css
>          max-width: 768px ;
зайвий пробіл

2024-01-12 19:14 UTC, VitaliyBogdanuk commented on src/css/style.css
>          max-width: 768px ;
зайвий пробіл

2024-01-12 19:14 UTC, VitaliyBogdanuk commented on src/css/style.css
>          width: 672px ;
зайвий пробіл

2024-01-12 19:14 UTC, VitaliyBogdanuk commented on src/css/style.css
>          margin: 0px 42px 50px 42px ;
зайвий пробіл

2024-01-12 19:14 UTC, VitaliyBogdanuk commented on src/css/style.css
>          width: 380px ;
зайвий пробіл

2024-01-12 19:14 UTC, VitaliyBogdanuk commented on src/css/style.css
> +        margin: 0 auto ;
зайвий пробіл

2024-01-12 19:14 UTC, VitaliyBogdanuk commented on src/css/style.css
> +        color: #000A24 ;
зайвий пробіл

2024-01-12 19:14 UTC, VitaliyBogdanuk commented on src/css/style.css
> +        float:right;
додайте пробіл

2024-01-12 19:14 UTC, VitaliyBogdanuk commented on src/css/style.css
> +        color: #000A24 ;
зайвий пробіл

2024-01-12 19:14 UTC, VitaliyBogdanuk commented on src/css/style.css
> +        margin-right: 48px ;
зайвий пробіл

2024-01-12 19:14 UTC, VitaliyBogdanuk commented on src/css/style.css
> +        margin-top: 29px ;
зайвий пробіл

2024-01-12 19:14 UTC, VitaliyBogdanuk commented on src/css/style.css
> +        margin-left: 42px ;
зайвий пробіл

2024-01-12 19:33 UTC, VitaliyBogdanuk commented
@DariaShkolnik conflict

2024-01-12 19:52 UTC, VitaliyBogdanuk requested changes

2024-01-12 19:52 UTC, VitaliyBogdanuk commented on src/css/style.css
> +    background: repeating-linear-gradient(90deg, black 0 5px,#0000 0 10px)
відсутня крапка з комою

2024-01-12 20:24 UTC, DariaShkolnik commented on src/css/style.css
> +    background: repeating-linear-gradient(90deg, black 0 5px,#0000 0 10px)
@VitaliyBogdanuk конфікти вирішила, ваші коментарі також виправила)

2024-01-12 20:35 UTC, merged