Applicant form
VinITAAcademy/b23_dv_dark pull request #33
Opened 2024-01-12 22:03 UTC by DariaShkolnik

2024-01-13 12:05 UTC, VitaliyBogdanuk commented
@DariaShkolnik conflict

2024-01-14 10:26 UTC, YevheniiRybin approved these changes

2024-01-14 10:26 UTC, YevheniiRybin approved these changes

2024-01-14 10:29 UTC, YevheniiRybin approved these changes

2024-01-14 10:33 UTC, YevheniiRybin requested changes
Код не завершений - робота над ним продовжується

2024-01-15 11:21 UTC, closed without merging