Dv 5 partners
VinITAAcademy/b23_dv_dark pull request #48
Opened 2024-01-15 20:23 UTC by leonestera

2024-01-15 20:26 UTC, YevheniiRybin requested changes
Потрібно замінити нижні підкреслення на дефіси у назвах блоків

2024-01-15 20:57 UTC, KateChens requested changes
Додала коментарі по коду. В цілому повтори в стилях та пропущені пробіли

2024-01-15 20:57 UTC, KateChens commented on src/css/style.css
> +    background: #000A24;
Кольори не у вигляді змінни. 628 і 629 стрічки

2024-01-15 20:57 UTC, KateChens commented on src/css/style.css
> +#partners .partners_main .partners_content .dotted_line{
загубили пробіл перед {

2024-01-15 20:57 UTC, KateChens commented on src/css/style.css
> +#partners .partners_main .partners_image{
загубили пробіл перед {

2024-01-15 20:57 UTC, KateChens commented on src/css/style.css
> +#partners .partners_main .partners_content .partners_content_text{
загубили пробіл перед {

2024-01-15 20:57 UTC, KateChens commented on src/css/style.css
> +    #partners .partners_main .partners_content .partners_content_text{
загубили пробіл перед {

2024-01-15 20:57 UTC, KateChens commented on src/css/style.css
> +        text-align: center;
в медіа можна не повторювати стилі, які були примінено на початку. воно вже знає про них. є сенс тільки перезаписувати які були вказані раніше чи писати нові

2024-01-15 20:57 UTC, KateChens commented on src/css/style.css
> +    #partners .partners_main .partners_content .dotted_line{
загубили пробіл перед {

2024-01-15 20:57 UTC, KateChens commented on src/css/style.css
> +    #partners .partners_main{
загубили пробіл перед {

2024-01-15 20:57 UTC, KateChens commented on src/css/style.css
> +    #partners .partners_main .partners_image{
загубили пробіл перед {

2024-01-15 20:57 UTC, KateChens commented on src/css/style.css
> +        margin-bottom: 25px;
margin-bottom - 2 рази
то яке значення має бути?

2024-01-15 20:57 UTC, KateChens commented on src/css/style.css
> +    #partners .partners_main .partners_content .partners_content_text{
пробіл пере {

2024-01-15 20:57 UTC, KateChens commented on src/css/style.css
> +    }
пробіл після }

2024-01-15 20:57 UTC, KateChens commented on src/css/style.css
> +    #partners .partners_main .partners_content .dotted_line{
пробіл пере {

2024-01-15 20:57 UTC, KateChens commented on index.html
> +            <img class="partners_image" src="src/assets/images/partners-block-logo.png" alt="stop killing">
треба відступ для img, адже він вкладений елемент у дів

2024-01-15 20:57 UTC, KateChens commented on index.html
> +      </section>
посунути </section> вліво, адже не видно вкладеність діва в нього

2024-01-15 20:57 UTC, KateChens commented on src/css/style.css
> +    margin: 0 auto;
margin, а потім окремо margin-bottom. Має бути все в 1 властивості

2024-01-15 20:57 UTC, KateChens commented on src/css/style.css
> +    margin: 0 auto;
margin, а потім окремо margin-bottom. Має бути все в 1 властивості

2024-01-16 20:56 UTC, YevheniiRybin requested changes
![Screenshot 2024-01-16 at 22 51 47](https://github.com/VinITAAcademy/b23_dv_dark/assets/144894131/2fa2369c-bcd7-4296-8e61-5be0e4c5424f)
Потрібно збільшити відстув. Зараз - два пробіли, має бути 4

Стрічки 612, 1555, 2298 - додати ланцюжок класів

2024-01-16 21:11 UTC, KateChens requested changes

2024-01-16 21:11 UTC, KateChens commented on index.html
>            </div>
ці 2 діва з 240 та 241 стрічки посунути на 1 таб, бо не на одному рівні відкриваючий та закриваючий тег одного діва

2024-01-16 21:11 UTC, KateChens commented on src/css/style.css
> +   /*  margin-bottom: 25px; */
цю стрічку можна видалити, марджін вже прописано

2024-01-16 21:11 UTC, KateChens commented on src/css/style.css
> +        margin-top: 30px;
властивість для марджіна 3 рази, длоя 3 сторін, можна записати в 1 стрічку

2024-01-17 08:42 UTC, YevheniiRybin approved these changes

2024-01-17 12:29 UTC, hollyts123 requested changes
1. Тут також краще прописати id 
![Screenshot_2](https://github.com/VinITAAcademy/b23_dv_dark/assets/58187694/5199a8e3-325b-4c80-958d-9c63cb04dd81)
![Screenshot_3](https://github.com/VinITAAcademy/b23_dv_dark/assets/58187694/b67b830a-4984-4567-9ca9-1fb8f0bbdb6e)

2. Перевірте, чи коректно ви прописали класи цим елементам. Бо клас однаковий і у контейнера, і у картинки. 
![Screenshot_1](https://github.com/VinITAAcademy/b23_dv_dark/assets/58187694/b4bb3e7e-6f79-4c1e-b772-0c6826824eaf)

2024-01-17 14:33 UTC, hollyts123 approved these changes

2024-01-17 18:32 UTC, KateChens approved these changes

2024-01-17 20:04 UTC, merged