Task/d 1 1
VinITAAcademy/b23_dv_dark pull request #49
Opened 2024-01-16 11:38 UTC by SergeyKorol1982

2024-01-16 11:45 UTC, YevheniiRybin approved these changes

2024-01-16 11:46 UTC, lizzccx approved these changes

2024-01-16 11:58 UTC, hollyts123 approved these changes

2024-01-16 12:48 UTC, YevheniiRybin requested changes
![Screenshot 2024-01-16 at 14 45 56](https://github.com/VinITAAcademy/b23_dv_dark/assets/144894131/5fdbd339-bc1c-402a-a16e-829cb0f21ac4)
Зміщуємо img праворуч

2024-01-16 12:50 UTC, YevheniiRybin requested changes
![Screenshot 2024-01-16 at 14 49 40](https://github.com/VinITAAcademy/b23_dv_dark/assets/144894131/294e02bf-4948-419a-a142-d17fcb927fdc)
Зміщуємо а праворуч

2024-01-16 12:52 UTC, YevheniiRybin requested changes
![Screenshot 2024-01-16 at 14 51 03](https://github.com/VinITAAcademy/b23_dv_dark/assets/144894131/324af325-3839-4826-8d05-3426cc961fc5)
p праворуч

2024-01-16 12:58 UTC, YevheniiRybin reviewed
![Screenshot 2024-01-16 at 14 57 14](https://github.com/VinITAAcademy/b23_dv_dark/assets/144894131/39a4a524-73c3-4f50-ac61-04438dc6c712)
ul (69-99) праворуч відносно div
li (70-98) - праворуч відносно ul

2024-01-16 13:01 UTC, YevheniiRybin requested changes
![Screenshot 2024-01-16 at 15 00 31](https://github.com/VinITAAcademy/b23_dv_dark/assets/144894131/5d30bbb0-e43c-49cb-87ad-41caf06c7897)
в js відсутнє вирівнювання

2024-01-16 13:04 UTC, YevheniiRybin reviewed
![Screenshot 2024-01-16 at 15 02 32](https://github.com/VinITAAcademy/b23_dv_dark/assets/144894131/79785e29-69a1-4711-a90c-3f56fd9908cd)
11 тут потрібно? Якщо ні, прибери будь ласка

2024-01-16 13:37 UTC, YevheniiRybin requested changes
![Screenshot 2024-01-16 at 15 32 18](https://github.com/VinITAAcademy/b23_dv_dark/assets/144894131/7f9d0145-03dc-4732-8ac3-8254614480e9)
додати ланцюжок стилів з id

![Screenshot 2024-01-16 at 15 32 52](https://github.com/VinITAAcademy/b23_dv_dark/assets/144894131/c9f14c6f-7931-4233-85a4-d9620eb11f86)
додати ланцюжок стилів з id

![Screenshot 2024-01-16 at 15 34 17](https://github.com/VinITAAcademy/b23_dv_dark/assets/144894131/0ea9e4dc-4d6b-4372-a091-4538125b022f)
додати id

![Screenshot 2024-01-16 at 15 35 34](https://github.com/VinITAAcademy/b23_dv_dark/assets/144894131/d2a02d64-1d7a-4687-a5ed-b3f92b38e322)
додати id

![Screenshot 2024-01-16 at 15 36 00](https://github.com/VinITAAcademy/b23_dv_dark/assets/144894131/e90f1731-d225-4e95-bb78-b3937434dbb1)
додати id

![Screenshot 2024-01-16 at 15 36 39](https://github.com/VinITAAcademy/b23_dv_dark/assets/144894131/1284e0dd-63d7-4025-b01d-da900f0fb0f8)
додати id

2024-01-16 13:38 UTC, YevheniiRybin reviewed
362 - 521 - додати ланцюжки з id

2024-01-16 13:41 UTC, YevheniiRybin requested changes
362 - 521, 1417, 1431, 1437, 1444, 1450, 1455 - 1467 - додати ланцюжок з id

2024-01-16 13:42 UTC, YevheniiRybin reviewed
![Screenshot 2024-01-16 at 15 41 39](https://github.com/VinITAAcademy/b23_dv_dark/assets/144894131/803a9f95-23c4-4f77-848e-4a2ef9eb28cf)
додати ланцюжок з id

2024-01-16 14:01 UTC, YevheniiRybin requested changes
![Screenshot 2024-01-16 at 16 00 28](https://github.com/VinITAAcademy/b23_dv_dark/assets/144894131/b84d3a2a-f759-4706-8a20-8651c4791100)
100 - зайвий таб
103 - зайвий таб

2024-01-16 14:10 UTC, YevheniiRybin requested changes
Я ж окремо нависав 100 і 103))
В 101 і 102 таб залишаємо

2024-01-16 14:13 UTC, YevheniiRybin approved these changes

2024-01-16 19:26 UTC, lizzccx approved these changes

2024-01-17 00:32 UTC, hollyts123 commented on index.html
> +            <ul class="desktop-list">
З тегом ul використовуємо li. У вас - button, огорнутий в a.
![Screenshot_2](https://github.com/VinITAAcademy/b23_dv_dark/assets/58187694/38d3f96d-c687-401a-b10a-cb5a71e9a73b)

2024-01-17 01:24 UTC, hollyts123 requested changes
1. З тегом ul використовуємо li. У вас - button, огорнутий в a
![1](https://github.com/VinITAAcademy/b23_dv_dark/assets/58187694/b8fdd73f-e271-4160-b1a4-1d70ab6f79e3)

2. Перевірити посилання
![2](https://github.com/VinITAAcademy/b23_dv_dark/assets/58187694/fc4c83cd-2834-4fbd-bf22-dcbf12f4ece5)

3. Передивитись та виправити структуру коду в цьому блоці:
- З ul використовуємо li.
- Навіщо огортати в li цілий div, який не є елементом списку? У вас li (ст. 80 та 95) відіграють роль контейнера та містять елементи, які не відносяться до списку.
![3](https://github.com/VinITAAcademy/b23_dv_dark/assets/58187694/2b5d09a8-4972-48cd-8cdd-ada235cb22ca)

4. Не потрібно кожного разу прописувати цей код
![4](https://github.com/VinITAAcademy/b23_dv_dark/assets/58187694/b9447935-0c63-4e85-927f-6815359b70f6)
Ви вже додали його вище:
![4-2](https://github.com/VinITAAcademy/b23_dv_dark/assets/58187694/639f0c3d-f06a-4a39-aa64-76966c5aab53)

5. Видалити код, що дублюється
![5](https://github.com/VinITAAcademy/b23_dv_dark/assets/58187694/d6a49d22-7ccf-4e2d-956e-8e03f17f3f8f)
![5-2](https://github.com/VinITAAcademy/b23_dv_dark/assets/58187694/e361a3ba-a045-490f-be28-d756de2bace2)

2024-01-17 11:10 UTC, SergeyKorol1982 commented
1. Виправлено
2. Посилання вірне
3. Виправлено
4. Виправлено

2024-01-17 13:04 UTC, hollyts123 requested changes
1. На що саме посилаєтесь? Ваш тег a не має атрибута href з посиланням.
![2](https://github.com/VinITAAcademy/b23_dv_dark/assets/58187694/ddb34f60-b715-4dcc-8efa-8a502da17b56)

2. Виправити структуру коду в цьому блоці, видалити зайві теги. 
![Screenshot_5](https://github.com/VinITAAcademy/b23_dv_dark/assets/58187694/577f3d7f-c00f-4ea1-bd6e-4a7b41bb2c6e)

2024-01-17 14:39 UTC, SergeyKorol1982 commented
структуру змінив, href  -  добавив

2024-01-17 14:59 UTC, hollyts123 commented on index.html
> +                <img class="intita-logo-img" href="#" src="./src/assets/images/Intita_logo.png" alt="intita_logo">
Не туди додали. Треба було додати до тегу a на ст. 73

2024-01-17 15:29 UTC, hollyts123 approved these changes

2024-01-17 15:35 UTC, merged