Task block 4
VinITAAcademy/b23_dv_dark pull request #5
Opened 2024-01-04 14:58 UTC by lizzccx

2024-01-04 18:46 UTC, VitaliyBogdanuk commented
@lizzccx 
перечитайте code conventions
Назви картинок
Написання стилів через ланцюжок для локалізації та зменшення конфліктів

2024-01-05 14:19 UTC, KateChens commented
1 При git commit пиши більш розширенні коментарі, щоб краще передавали суть зробленого.
2 Називай класи не просто main, block, а додай унікальне слово, що вкаже, що за блок, типу: conditions-main-block, conditions-main-block-text-2
3 Так само для картинки з класом img1 краще надати класи типу: conditions-main-block-img1
4 style.css стрічка 206, 210, 215 .. Немає пробілу після двокрапки. Використай бьютіфай.
5 При використанні шрифта немає потреби писати його вагу, вона вже врахована. Наприкад код
    font-family: 'Ubuntu Regular';
    font-weight: 500;
Можна замінити на:
    font-family: 'Ubuntu Medium';
Ознайомитись зі шрифтами, назвами і вагою можна зверху style.css.
6 507 чи 508 стрічка в стилях - зайвий пробіл, так само 514

2024-01-05 15:13 UTC, KateChens requested changes
1 При git commit пиши більш розширенні коментарі, щоб краще передавали суть зробленого.
2 Називай класи не просто main, block, а додай унікальне слово, що вкаже, що за блок, типу: conditions-main-block, conditions-main-block-text-2
3 Так само для картинки з класом img1 краще надати класи типу: conditions-main-block-img1
4 style.css стрічка 206, 210, 215 .. Немає пробілу після двокрапки. Використай бьютіфай.
5 При використанні шрифта немає потреби писати його вагу, вона вже врахована. Наприкад код
font-family: 'Ubuntu Regular';
font-weight: 500;
Можна замінити на:
font-family: 'Ubuntu Medium';
Ознайомитись зі шрифтами, назвами і вагою можна зверху style.css.
6 507 чи 508 стрічка в стилях - зайвий пробіл, так само 514

2024-01-05 15:13 UTC, YevheniiRybin approved these changes

2024-01-05 15:43 UTC, VitaliyBogdanuk commented
@lizzccx @hollyts123 
conflict

2024-01-05 20:26 UTC, hollyts123 approved these changes

2024-01-05 23:57 UTC, KateChens approved these changes

2024-01-06 07:05 UTC, merged