develop_Mentors_questionnaire
VinITAAcademy/b23_dv_dark pull request #54
Opened 2024-01-17 22:49 UTC by lizzccx

2024-01-18 10:42 UTC, VitaliyBogdanuk requested changes

2024-01-18 10:42 UTC, VitaliyBogdanuk commented on index.html
> +                    <h2 class="questionnaire-mentors-title">Анкета для <span
А чому б просто не обгорнути в тег <b> замість спана?

2024-01-18 10:42 UTC, VitaliyBogdanuk commented on src/css/style.css
> +    width: 677px !important;
поплило вирівнювання нижче

2024-01-18 10:42 UTC, VitaliyBogdanuk commented on src/css/style.css
> +    max-width: 677px !important;
чому ви використовуєте імпортант?

2024-01-18 10:42 UTC, VitaliyBogdanuk commented on src/css/style.css
> +    width: 677px !important;
те саме, поплило вирівнювання та чому використовується імпортант?

2024-01-18 10:42 UTC, VitaliyBogdanuk commented on src/css/style.css
> +    margin-top: 20px;
передивіться всі марджини в стилях, ви прописуєте марджин топ а нижче одразу ставите його = 0, пишіть марджини в одну стрічку.

2024-01-18 17:09 UTC, YevheniiRybin requested changes

2024-01-18 17:09 UTC, YevheniiRybin commented on index.html
>                          програми</h2>
тег h2 зайвий? на його місці має бути b?

2024-01-18 17:09 UTC, YevheniiRybin commented on src/css/style.css
> +      margin-top: 30px;
записуємо margin в одну стрічку

2024-01-18 17:09 UTC, YevheniiRybin commented on src/css/style.css
> +      margin-bottom: 30px;
записуємо margin в одну стрічку

2024-01-18 17:09 UTC, YevheniiRybin commented on src/css/style.css
> +       margin-top: 30px;
записуємо margin в одну стрічку

2024-01-19 11:46 UTC, VitaliyBogdanuk commented
@lizzccx @hollyts123 conflict

2024-01-19 15:35 UTC, merged