add pixel perfect to dv-7-specialty
VinITAAcademy/b23_dv_dark pull request #55
Opened 2024-01-17 23:28 UTC by KateChens

Додала pixel perfect до блоку спеціалізацій, пройшлась по доку поправити пробіли, відступи, пару марджінів в 1 записала

2024-01-18 07:51 UTC, YevheniiRybin approved these changes

2024-01-18 10:25 UTC, VitaliyBogdanuk requested changes

2024-01-18 10:29 UTC, KateChens commented on src/js/script.js
> +    document.addEventListener('resize', function (e) {
Хороше запитання. Тестила як буде працювати і так і так
Як розумію краще залишити минулий варіант

2024-01-18 10:32 UTC, KateChens commented on src/js/script.js
> +    document.addEventListener('resize', function (e) {
Хоча по роботі мені більше document подобається) Краще він

2024-01-18 10:56 UTC, VitaliyBogdanuk commented on src/js/script.js
> +    document.addEventListener('resize', function (e) {
Ну почитайте ще як працює перше та друге, та дасте мені пояснення чому потрібно використати саме те що ви використали або щось інше. Бо "мені подобається більше" не пояснення, варто зрозуміти сам процес )

2024-01-18 11:00 UTC, KateChens commented on src/js/script.js
> +    document.addEventListener('resize', function (e) {
Обрала документ, бо віндоу не завжди коректно працює. В цілому документ це видима частина, тому він краще підходить. Адже змінюємо її розмір

2024-01-19 11:46 UTC, VitaliyBogdanuk commented
@KateChens @hollyts123 conflict

2024-01-19 15:36 UTC, merged