Dv 16 developers page
VinITAAcademy/b23_dv_dark pull request #56
Opened 2024-01-18 20:33 UTC by YevheniiRybin

2024-01-18 21:01 UTC, SergeyKorol1982 reviewed
Відступи 8, повинні бути 4
В тому що я знаю, помилок не побачив)

2024-01-18 21:11 UTC, KateChens requested changes

2024-01-18 21:11 UTC, KateChens commented on developers.html
> +				href="https://www.linkedin.com/in/lesia-korol-9059472a3?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app">
може краще посилання у форматі https://www.linkedin.com/in/lesia-korol-9059472a3/ ?

2024-01-18 21:11 UTC, KateChens commented on developers.html
> +		<div class="container-students-laptop">
це так треба що в розділі тім лід 4 людини, а тут 2? типу візуально розділяється?

2024-01-18 21:21 UTC, YevheniiRybin commented on developers.html
> +	<meta charset="UTF-8">
Не знаю чому з'явилися відступи. В мене виглядає так
![Screenshot 2024-01-18 at 22 59 13](https://github.com/VinITAAcademy/b23_dv_dark/assets/144894131/0a5b3852-5a5a-4a90-a862-eae91e4d142f)

2024-01-18 21:24 UTC, YevheniiRybin commented on developers.html
> +					UA
Думаю UA має бути в тезі щоб вести та українськомовну версію сторінки в ангомовній версії сторінки))

2024-01-18 21:27 UTC, YevheniiRybin commented on developers.html
> +				<div class=" translate translate-one">EN</div>
done

2024-01-18 21:27 UTC, YevheniiRybin commented on developers.html
> +				href="https://www.linkedin.com/in/lesia-korol-9059472a3?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app">
done
Дякую!

2024-01-18 21:28 UTC, KateChens commented on developers.html
> +					UA
бо поки ЮА не в а

2024-01-18 21:30 UTC, YevheniiRybin commented on developers.html
> +		<div class="container-students-laptop">
Вони просто на різних стрічках
![Screenshot 2024-01-18 at 23 28 37](https://github.com/VinITAAcademy/b23_dv_dark/assets/144894131/418dc9f6-7c57-46af-8367-2c63311050d0)

2024-01-18 21:35 UTC, KateChens commented on developers.html
> +		<div class="container-students-laptop">
зрозуміла, ок

2024-01-19 10:44 UTC, KateChens approved these changes

2024-01-19 12:37 UTC, YevheniiRybin commented
> Відступи 8, повинні бути 4 В тому що я знаю, помилок не побачив)

Змінив на 4. Це були налаштування гіта саме на цьому файлі

2024-01-19 13:02 UTC, SergeyKorol1982 approved these changes

2024-01-19 15:35 UTC, merged