Success modal
VinITAAcademy/b23_dv_dark pull request #6
Opened 2024-01-04 19:42 UTC by DariaShkolnik

2024-01-04 21:57 UTC, YevheniiRybin reviewed
Згідно code_conventions маємо для розміру шрифтів використовувати rem/em

Prefer using rem and em units for font sizes

7. Prefer using rem and em units for font sizes.
   - ❌ Wrong: `font-size: 16px;`
 - ✔️ Correct: `font-size: 1rem;`

2024-01-05 00:24 UTC, KateChens reviewed
1. Чому в файлі html є стиль? style="width: 375px;"
2. Іконка закриття форми (хрестик) у нас завантажена як шрифт з айкомун. Треба лише використати клас icon-close та налаштувати розмір та кольори.
3. Кнопку для тесту відкриття форми варто закоментувати.
4. Дрібничка, проте в style.css одна зі стрічок 236 чи 237 - зайві. І 257 - 258. 269 - 270.
5. font-weight можна не прописувати, адже він у нас прописаний на самому початку відповідно до ваги шрифта. Головне використовувати відповідну назву шрифта у font-family.
А так круто, молодець)

2024-01-05 10:30 UTC, YevheniiRybin approved these changes

2024-01-05 13:54 UTC, KateChens approved these changes

2024-01-05 14:34 UTC, hollyts123 requested changes
Пропишіть повністю ланцюжок стилів

2024-01-05 15:37 UTC, hollyts123 approved these changes

2024-01-05 15:44 UTC, DariaShkolnik commented on index.html
> +    <!-- I have added it to test open of succees modal -->
ok

2024-01-05 15:45 UTC, DariaShkolnik commented on index.html
> +    <!-- I have added it to test open of succees modal -->
тоді мені потрібно переробити, чи вже хай так буде ?

2024-01-05 15:49 UTC, VitaliyBogdanuk commented on index.html
> +    <!-- I have added it to test open of succees modal -->
"хай так буде" - в мене не працює, зробіть правки та закомітьте.

2024-01-05 15:49 UTC, hollyts123 commented on index.html
> +    <!-- I have added it to test open of succees modal -->
> тоді мені потрібно переробити, чи вже хай так буде ?

Потрібно переробити згідно вказаному коментарю.

2024-01-05 15:50 UTC, DariaShkolnik commented on index.html
> +    <!-- I have added it to test open of succees modal -->
ок зараз буде все

2024-01-05 19:23 UTC, DariaShkolnik commented on index.html
> +    <!-- I have added it to test open of succees modal -->
@VitaliyBogdanuk готово

2024-01-08 09:07 UTC, merged