Adoptiv work
VinITAAcademy/b23_dv_dark pull request #70
Opened 2024-01-21 20:30 UTC by leonestera

2024-01-21 20:39 UTC, KateChens requested changes

2024-01-21 20:39 UTC, KateChens commented on src/css/style.css
> +    }
Зробіть ентер між стилями

2024-01-21 20:39 UTC, KateChens commented on src/css/style.css
> +    margin: 25px 0 25px 49px;
не дуже зрозуміла цей стиль, адже лінії і так нормально виглядали

2024-01-21 21:32 UTC, YevheniiRybin requested changes
Думаю, буде краще, якщо будеш мерджити в develop замість main)

2024-01-22 11:14 UTC, VitaliyBogdanuk commented
@leonestera @hollyts123 
ПР в мейн гілку, відхиляю

2024-01-22 11:14 UTC, closed without merging