Task/dv 1 dv 11
VinITAAcademy/b23_dv_dark pull request #75
Opened 2024-01-23 14:57 UTC by SergeyKorol1982

2024-01-23 15:29 UTC, YevheniiRybin requested changes

2024-01-23 15:29 UTC, YevheniiRybin commented on index.html
> -        </section>
div "hero_main" наче не має закриваючого тега. Перевір, будь ласка.

2024-01-23 15:39 UTC, YevheniiRybin approved these changes

2024-01-23 16:16 UTC, KateChens requested changes

2024-01-23 16:16 UTC, KateChens commented on src/css/style.css
> +    margin-left: 8px;
margin об'єднати в 1 стрічку

2024-01-23 16:16 UTC, KateChens commented on src/css/style.css
> +    margin-left: 12px;
margin об'єднати в 1 стрічку

2024-01-23 16:16 UTC, KateChens commented on src/css/style.css
> +    margin-top: 12px;
margin об'єднати в 1 стрічку

2024-01-23 16:16 UTC, KateChens commented on src/css/style.css
> +    margin-top: 12px;
margin об'єднати в 1 стрічку

2024-01-23 16:16 UTC, KateChens commented on src/css/style.css
> +    margin-left: 8px;
margin об'єднати в 1 стрічку

2024-01-23 16:16 UTC, KateChens commented on src/css/style.css
> +
зайва стрічка

2024-01-23 16:16 UTC, KateChens commented on src/css/style.css
> +    left: 27px
нема крапки з комою

2024-01-23 16:16 UTC, KateChens commented on src/css/style.css
> +
зайва стрічка

2024-01-23 16:16 UTC, KateChens commented on src/css/style.css
> +
зайва стрічка

2024-01-23 16:16 UTC, KateChens commented on src/js/script.js
> +        // start specialities
відступи щось по 8 пробілів, а не 4

2024-01-23 16:16 UTC, KateChens commented on src/js/script.js
> +        let carouselBlock=document.querySelector('.specialty-carousel-main-container');
По code_conventions - Place spaces before and after operators. Форматування це прибрало

2024-01-23 16:16 UTC, KateChens commented on src/js/script.js
> +        let carouselBlock=document.querySelector('.specialty-carousel-main-container');
Поверніть як було)

2024-01-23 16:16 UTC, KateChens commented on src/js/script.js
> +        );
тут теж }); мало бути в 1 стрічці

2024-01-23 17:13 UTC, VitaliyBogdanuk commented
@SergeyKorol1982 @hollyts123 
conflict

2024-01-23 19:03 UTC, KateChens requested changes

2024-01-23 19:03 UTC, KateChens commented on index.html
> +                    <p class="cards-item__text">
випадково скопіювали другий раз

2024-01-23 19:37 UTC, KateChens approved these changes

2024-01-24 10:45 UTC, hollyts123 commented on index.html
>                          </h2>
Передивитись та виправити теги. Зараз у вашого div закриваючий елемент h2...

2024-01-24 11:06 UTC, hollyts123 commented on src/css/style.css
> +    left: 27px
Додати крапку з комою

2024-01-24 11:14 UTC, hollyts123 requested changes
Відсутня крапка з комою в style.css в рядку 2169

2024-01-24 11:21 UTC, SergeyKorol1982 commented
виправив

2024-01-24 11:25 UTC, hollyts123 approved these changes

2024-01-24 13:11 UTC, VitaliyBogdanuk commented
@SergeyKorol1982 conflict

2024-01-24 19:13 UTC, SergeyKorol1982 commented
Конфлікт вирішив
Зауваження виправив

2024-01-25 12:45 UTC, merged