Bugs/dv 16 developers page
VinITAAcademy/b23_dv_dark pull request #77
Opened 2024-01-23 20:35 UTC by YevheniiRybin

2024-01-23 21:48 UTC, KateChens requested changes

2024-01-23 21:48 UTC, KateChens commented on src/css/developers.css
> +    min-width: 357pxgit;
опечатка

2024-01-23 21:48 UTC, KateChens commented on src/css/developers.css
> +    padding: 16px 57px 16px 57px;
тоді можна вже 2 значення а не 4

2024-01-23 21:48 UTC, KateChens commented on src/css/developers.css
> +        padding: 16px 21px 16px 21px;
і тут

2024-01-23 21:48 UTC, KateChens commented on index.html
> +		</div>
а що за дів?

2024-01-23 22:09 UTC, YevheniiRybin commented on src/css/developers.css
> +    min-width: 357pxgit;
так
виправив

2024-01-23 22:09 UTC, YevheniiRybin commented on src/css/developers.css
> +    padding: 16px 57px 16px 57px;
скоротив

2024-01-23 22:09 UTC, YevheniiRybin commented on src/css/developers.css
> +        padding: 16px 21px 16px 21px;
скоротив

2024-01-23 22:18 UTC, YevheniiRybin commented on index.html
> +		</div>
Помітив, що не було закриваючого тега для div з класом hero_main", тому додав

2024-01-23 22:48 UTC, KateChens approved these changes

2024-01-24 09:44 UTC, lizzccx approved these changes

2024-01-24 11:22 UTC, hollyts123 approved these changes

2024-01-24 12:23 UTC, merged